### ISSUE TITLE
'meteor add' gives '404 Not Found'

### ISSUE THREAD

**Issue by hellogerard** [sebakerckhof/stratosphere#5]
I have my Stratosphere app up & running with a private package listed.

I tried adding a package to a test project (using the environment var) and am getting a long trace:

```
Error: 404 Not Found

    at Error (<anonymous>)
    at Object._.extend.getUrl (/tools/utils/http-helpers.js:334:13)
    at [object Object]._.extend._downloadBuildToTempDir (/tools/packaging/tropohouse.js:301:38)
    at /tools/packaging/tropohouse.js:483:39
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at /tools/packaging/tropohouse.js:479:24
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/gerard/.meteor/packages/meteor-tool/.1.1.9.18n0e34++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/packaging/tropohouse.js:478:11
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at Object.download (/tools/packaging/tropohouse.js:437:20)
    at /tools/packaging/tropohouse.js:575:22
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:572:20)
    at /tools/project-context.js:702:25
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at /tools/project-context.js:701:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (/tools/project-context.js:700:13)
    at /tools/project-context.js:257:35
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
    at /tools/cli/commands-packages.js:1996:20
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:1995:27)
    at /tools/cli/main.js:1378:23
```

Any help? So close!

_Update:_ Meant to add that `meteor search` and `meteor show` work fine with Stratosphere packages.

**Comment by sebakerckhof** [comment]
Hmmm, I changed the location where files are uploaded too in beta 1. So probably I forgot to change the download url somewhere. So meteor tries to download the package sources from the wrong location.
I'll have a fix soon.

Sorry that things are a bit bumpy. Beta1 was a major rewrite from the alpha version and I didn't really test everything yet.

**Comment by hellogerard** [comment]
No problem. This would solve a huge need at our company. We want to share code via packages, but they're not suitable for the public. And even if they were, we don't necessarily want to maintain them. Nice work.

**Comment by sebakerckhof** [comment]
Yeah, that's why it's made. + it allows you to overwrite existing packages (e.g. you want a custom version of DDP).

Anyway, should be fixed. However, you'll have to publish a new version of your package or unpublish it via the GUI and republish it.
